#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod erc20;
pub mod pink_lock;
pub mod trust_swap_lp_locker;
pub mod uncx_lp_locker;
pub mod uniswap_v2_factory;
pub mod uniswap_v2_pair;
pub mod uniswap_v2_pair_factory;
pub mod uniswap_v2_permits;
pub mod uniswap_v2_router;
